import type { SignalDefinition } from './types';

export const SIGNAL_DEFINITIONS: readonly SignalDefinition[] = [
  { key: 'pvPowerState', semanticId: 'pv.power', label: 'PV-Leistung aktuell', category: 'energy', required: true, historyRequired: true, unit: 'W', historicalKey: 'historicalPvPowerState', description: 'Aktuelle produktive PV-Leistung aus ekd-solar; ältere Solar-State-Familie dient nur der Historie.' },
  { key: 'housePowerState', semanticId: 'house.power', label: 'Hausverbrauch aktuell', category: 'energy', required: true, historyRequired: true, unit: 'W', historicalKey: 'historicalHousePowerState', description: 'Gesamter Hausverbrauch; ein separater Wärmepumpenzähler ist derzeit nicht vorhanden.' },
  { key: 'gridPowerState', semanticId: 'grid.power_signed', label: 'Netzleistung signed', category: 'energy', required: true, historyRequired: true, unit: 'W', description: 'Vorzeichenbehaftete Netzleistung des produktiven ekd-solar Adapters.' },
  { key: 'batteryPowerState', semanticId: 'battery.power_signed', label: 'Batterieleistung signed', category: 'energy', required: true, historyRequired: true, unit: 'W', description: 'Positiv = Entladen, negativ = Laden.' },
  { key: 'batterySocState', semanticId: 'battery.soc', label: 'Batterie-SOC', category: 'energy', required: true, historyRequired: true, unit: '%', historicalKey: 'historicalBatterySocState', description: 'Ladezustand der 20-kWh-Batterie.' },
  { key: 'dhwTemperatureState', semanticId: 'dhw.temperature', label: 'Warmwassertemperatur', category: 'heatpump', required: true, historyRequired: true, unit: '°C', description: 'Aktuelle Speichertemperatur; später bevorzugt über vcontrold.' },
  { key: 'dhwNormalTargetState', semanticId: 'dhw.target.normal', label: 'Warmwasser-Soll normal', category: 'heatpump', required: true, historyRequired: true, unit: '°C', description: 'Normaler Viessmann-Warmwasser-Sollwert.' },
  { key: 'dhwTemp2TargetState', semanticId: 'dhw.target.temp2', label: 'Warmwasser-Soll temp-2', category: 'heatpump', required: true, historyRequired: true, unit: '°C', description: 'Erhöhter Sollwert; Nutzung bleibt durch Sicherheits- und Komfortregeln begrenzt.' },
  { key: 'dhwChargingState', semanticId: 'dhw.charging', label: 'Warmwasserbereitung aktiv', category: 'heatpump', required: true, historyRequired: true, description: 'Kennzeichnet reale Warmwasser-Ladeereignisse für das physikalische Modell.' },
  { key: 'compressorActiveState', semanticId: 'heatpump.compressor_active', label: 'Kompressor aktiv', category: 'heatpump', required: true, historyRequired: true, description: 'Aktivstatus des Verdichters.' },
  { key: 'compressorModulationState', semanticId: 'heatpump.compressor_modulation', label: 'Kompressor-Modulation', category: 'heatpump', required: false, historyRequired: true, unit: '%', description: 'Cloud-Signal als Übergang; exakte Leistungswerte werden später lokal ergänzt.' },
  { key: 'hk1SupplyTemperatureState', semanticId: 'hk1.supply_temperature', label: 'HK1 Vorlauf', category: 'heatpump', required: true, historyRequired: true, unit: '°C', description: 'Direkter HK1-Vorlauf. Nicht mit dem vermutlich HK2-/Sekundärkreis-Signal verwechseln.' },
  { key: 'returnTemperatureState', semanticId: 'heating.return_temperature', label: 'Heizungsrücklauf', category: 'heatpump', required: true, historyRequired: true, unit: '°C', description: 'Rücklauftemperatur für das Gebäudemodell.' },
  { key: 'hk1PumpState', semanticId: 'hk1.pump', label: 'HK1 Pumpe', category: 'heatpump', required: true, historyRequired: true, description: 'Pumpenstatus für die Erkennung realer Heizphasen.' },
  { key: 'hk1ScheduleState', semanticId: 'hk1.schedule_snapshot', label: 'HK1 Schedule Cache', category: 'heatpump', required: true, historyRequired: true, description: 'Read-only Baseline-Snapshot des bestehenden Heizplans.' },
  { key: 'indoorTemperatureState', semanticId: 'climate.indoor_temperature', label: 'Innentemperatur (Sainlogic)', category: 'climate', required: true, historyRequired: true, unit: '°C', description: 'Primärsensor. Bei Ausfall wird der Mittelwert frischer, gültiger ESPHome-Sensoren verwendet.' },
  { key: 'outsideTemperatureState', semanticId: 'climate.outside_temperature', label: 'Außentemperatur', category: 'climate', required: true, historyRequired: true, unit: '°C', description: 'Realer Klimazustand statt harter Kalenderjahreszeit.' },
  { key: 'solarRadiationState', semanticId: 'climate.solar_radiation', label: 'Solarstrahlung', category: 'climate', required: true, historyRequired: true, unit: 'W/m²', description: 'Passive solare Gewinne und Wetterregime.' },
  { key: 'pvForecastState', semanticId: 'forecast.pv', label: 'PV-Prognose JSON', category: 'forecast', required: true, historyRequired: true, description: 'Historische Forecast-Snapshots sind erforderlich, damit Backtests keine Ist-Werte aus der Zukunft verwenden.' },
  { key: 'pvForecastIssuedAtState', semanticId: 'forecast.pv_issued_at', label: 'PV-Prognose Ausgabezeit', category: 'forecast', required: true, historyRequired: true, description: 'Trennt Forecast-Ausgabezeit und prognostizierten Zeitraum.' },
  { key: 'weatherForecastState', semanticId: 'forecast.weather', label: 'Wetterprognose JSON', category: 'forecast', required: false, historyRequired: true, description: 'Temperatur-, Strahlungs- und Bewölkungsprognose, falls verfügbar.' },
  { key: 'holidayState', semanticId: 'context.holiday', label: 'Feiertag', category: 'context', required: false, historyRequired: true, description: 'Kontext für das Nutzungs-/Bedarfsmodell.' }
] as const;

export const HISTORICAL_ONLY_SIGNALS: readonly SignalDefinition[] = [
  { key: 'historicalGridImportState', semanticId: 'history.grid_import', label: 'Historischer Netzbezug', category: 'energy', required: false, historyRequired: true, description: 'Alte Solar-State-Familie für die Zeit vor ekd-solar.' },
  { key: 'historicalGridExportState', semanticId: 'history.grid_export', label: 'Historische Einspeisung', category: 'energy', required: false, historyRequired: true, description: 'Alte Solar-State-Familie für die Zeit vor ekd-solar.' },
  { key: 'historicalBatteryChargeState', semanticId: 'history.battery_charge', label: 'Historische Batterieladung', category: 'energy', required: false, historyRequired: true, description: 'Getrennter Alt-State für die historische signed-Ableitung.' },
  { key: 'historicalBatteryDischargeState', semanticId: 'history.battery_discharge', label: 'Historische Batterieentladung', category: 'energy', required: false, historyRequired: true, description: 'Getrennter Alt-State für die historische signed-Ableitung.' }
] as const;

export const VCONTROLD_SIGNALS: readonly SignalDefinition[] = [
  { key: 'vcontroldDhwTemperatureState', semanticId: 'vcontrold.dhw.temperature', label: 'vcontrold Warmwassertemperatur', category: 'migration', required: false, historyRequired: true, unit: '°C', description: 'Lokaler Ersatzkandidat für die Cloud-Warmwassertemperatur.' },
  { key: 'vcontroldHk1SupplyTemperatureState', semanticId: 'vcontrold.hk1.supply_temperature', label: 'vcontrold HK1 Vorlauf', category: 'migration', required: false, historyRequired: true, unit: '°C', description: 'Lokaler Ersatzkandidat für den Cloud-HK1-Vorlauf.' },
  { key: 'vcontroldReturnTemperatureState', semanticId: 'vcontrold.heating.return_temperature', label: 'vcontrold Rücklauf', category: 'migration', required: false, historyRequired: true, unit: '°C', description: 'Lokaler Ersatzkandidat für den Cloud-Rücklauf.' },
  { key: 'vcontroldHk1PumpState', semanticId: 'vcontrold.hk1.pump', label: 'vcontrold HK1 Pumpe', category: 'migration', required: false, historyRequired: true, description: 'Lokaler Ersatzkandidat für den Cloud-Pumpenstatus.' },
  { key: 'vcontroldHeatpumpPowerState', semanticId: 'vcontrold.heatpump.total_power', label: 'vcontrold Wärmepumpenleistung', category: 'migration', required: false, historyRequired: true, unit: 'W', description: 'Exakte lokale elektrische Gesamtaufnahme.' },
  { key: 'vcontroldCompressorPowerState', semanticId: 'vcontrold.heatpump.compressor_power', label: 'vcontrold Kompressorleistung', category: 'migration', required: false, historyRequired: true, unit: 'W', description: 'Exakte lokale elektrische Kompressoraufnahme.' },
  { key: 'vcontroldElectricHeaterPowerState', semanticId: 'vcontrold.heatpump.electric_heater_power', label: 'vcontrold Heizstableistung', category: 'migration', required: false, historyRequired: true, unit: 'W', description: 'Exakte lokale elektrische Heizstabaufnahme.' },
  { key: 'vcontroldCompressorModulationState', semanticId: 'vcontrold.heatpump.compressor_modulation', label: 'vcontrold Kompressor-Modulation', category: 'migration', required: false, historyRequired: true, unit: '%', description: 'Lokale Verdichterfrequenz oder Modulation.' }
] as const;
